import { randomUUID } from "node:crypto";
import pg from "pg";
const { Pool }=pg;

const SCRIPT_PATTERNS=[/<\s*script\b/i,/javascript\s*:/i,/on(?:error|load|click)\s*=/i,/<\s*iframe\b/i,/data\s*:\s*text\/html/i];
const PHISHING_PATTERNS=[/podaj\s+(?:mi\s+)?has[łl]o/i,/wy[śs]lij\s+(?:mi\s+)?kod\s+(?:2fa|mfa|sms|logowania)/i,/verify\s+your\s+password/i];
const RESERVED_NAMES=/^(admin|administrator|moderator|support|gracz(?:\.pl)?|system|owner|właściciel)$/i;

export class ModerationError extends Error{constructor(message="Treść została zablokowana przez filtr bezpieczeństwa."){super(message);this.name="ModerationError";this.code="MODERATION_BLOCKED";this.status=400;}}
export class ModerationService{
  constructor(databaseUrl=null,{audit=null}={}){this.pool=databaseUrl?new Pool({connectionString:databaseUrl,ssl:databaseUrl.includes("localhost")||databaseUrl.includes("127.0.0.1")?false:{rejectUnauthorized:false},max:2}):null;this.audit=audit;this.memory=[];this.ready=this.pool?this.initialize():Promise.resolve();}
  async initialize(){await this.pool.query(`CREATE TABLE IF NOT EXISTS gracz_moderation_decisions(decision_id UUID PRIMARY KEY,user_id VARCHAR(32),context VARCHAR(32) NOT NULL,outcome VARCHAR(16) NOT NULL,reason VARCHAR(64),content_hash CHAR(64),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await this.pool.query(`CREATE TABLE IF NOT EXISTS gracz_moderation_appeals(appeal_id UUID PRIMARY KEY,decision_id UUID NOT NULL REFERENCES gracz_moderation_decisions(decision_id) ON DELETE CASCADE,user_id VARCHAR(32) NOT NULL,explanation TEXT NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'open',reviewed_by VARCHAR(32),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),reviewed_at TIMESTAMPTZ)`);}
  assessText(value,{context="message"}={}){const text=String(value??"").replace(/\u0000/g,"").trim();if(!text)return{allowed:true,text};if(SCRIPT_PATTERNS.some(r=>r.test(text)))return{allowed:false,reason:"active-content"};if(PHISHING_PATTERNS.some(r=>r.test(text)))return{allowed:false,reason:"credential-phishing"};const links=(text.match(/https?:\/\//gi)||[]).length;if(context==="message"&&links>4)return{allowed:false,reason:"link-spam"};if(context==="chat"&&links>2)return{allowed:false,reason:"link-spam"};return{allowed:true,text};}
  assessName(value){const text=String(value??"").trim();if(RESERVED_NAMES.test(text))return{allowed:false,reason:"reserved-identity"};if(/[<>]/.test(text))return{allowed:false,reason:"markup-in-name"};return{allowed:true,text};}
  async enforce({userId=null,context,value}){const result=context==="nick"?this.assessName(value):this.assessText(value,{context});if(result.allowed)return result.text;const decisionId=randomUUID();await this.record({decisionId,userId,context,outcome:"blocked",reason:result.reason});await this.audit?.record({actorId:userId,eventType:"moderation.blocked",outcome:"failure",targetType:context,metadata:{reason:result.reason}});throw Object.assign(new ModerationError(),{decisionId,reason:result.reason});}
  async record({decisionId=randomUUID(),userId,context,outcome,reason}){if(!this.pool){this.memory.push({decisionId,userId,context,outcome,reason});return decisionId;}await this.ready;await this.pool.query(`INSERT INTO gracz_moderation_decisions(decision_id,user_id,context,outcome,reason) VALUES($1,$2,$3,$4,$5)`,[decisionId,userId||null,context,outcome,reason||null]);return decisionId;}
  async appeal({decisionId,userId,explanation}){const text=String(explanation||"").trim().slice(0,2000);if(text.length<10)throw new ModerationError("Odwołanie musi zawierać co najmniej 10 znaków.");const appealId=randomUUID();if(this.pool){await this.ready;const decision=await this.pool.query(`SELECT 1 FROM gracz_moderation_decisions WHERE decision_id=$1 AND user_id=$2`,[decisionId,userId]);if(!decision.rowCount)throw new ModerationError("Nie znaleziono decyzji należącej do tego konta.");await this.pool.query(`INSERT INTO gracz_moderation_appeals(appeal_id,decision_id,user_id,explanation) VALUES($1,$2,$3,$4)`,[appealId,decisionId,userId,text]);}await this.audit?.record({actorId:userId,eventType:"moderation.appeal.created",targetType:"moderation-decision",targetId:decisionId});return{appealId,status:"open"};}
  async close(){if(this.pool)await this.pool.end();}
}

export function withAccountModeration(accounts,moderation){return new Proxy(accounts,{get(target,prop){const original=target[prop];if(typeof original!=="function")return original;
  if(prop==="register")return async input=>{await moderation.enforce({userId:null,context:"nick",value:input?.userId});await moderation.enforce({userId:null,context:"nick",value:input?.displayName});try{const result=await target.register(input);await moderation.audit?.record({actorId:result?.userId||input?.userId,eventType:"account.registered",targetType:"account",targetId:result?.userId||input?.userId});return result;}catch(error){await moderation.audit?.record({actorId:input?.userId||null,eventType:error?.code==="VERIFICATION_REQUIRED"?"account.registration.pending-verification":"account.registration.failed",outcome:error?.code==="VERIFICATION_REQUIRED"?"success":"failure",targetType:"account",targetId:input?.userId||null,metadata:{code:error?.code||"ERROR"}});throw error;}};
  if(prop==="authenticate")return async input=>{try{const result=await target.authenticate(input);await moderation.audit?.record({actorId:result?.userId||input?.userId,eventType:input?.verificationCode!==undefined?"account.activation.verified":"auth.login",targetType:"account",targetId:result?.userId||input?.userId});return result;}catch(error){await moderation.audit?.record({actorId:input?.userId||null,eventType:input?.verificationCode!==undefined?"account.activation.failed":"auth.login",outcome:"failure",targetType:"account",targetId:input?.userId||null,metadata:{code:error?.code||"ERROR"}});throw error;}};
  if(prop==="resetPasswordWithEmail")return async input=>{try{const result=await target.resetPasswordWithEmail(input);await moderation.audit?.record({actorId:input?.userId,eventType:"account.password.reset",targetType:"account",targetId:input?.userId});return result;}catch(error){await moderation.audit?.record({actorId:input?.userId||null,eventType:"account.password.reset",outcome:"failure",targetType:"account",targetId:input?.userId||null,metadata:{code:error?.code||"ERROR"}});throw error;}};
  if(prop==="updateProfile")return async(userId,input)=>{if(input?.displayName!==undefined)await moderation.enforce({userId,context:"nick",value:input.displayName});const result=await target.updateProfile(userId,input);await moderation.audit?.record({actorId:userId,eventType:"account.profile.updated",targetType:"account",targetId:userId,metadata:{displayNameChanged:Object.prototype.hasOwnProperty.call(input||{},"displayName"),emailChanged:Object.prototype.hasOwnProperty.call(input||{},"email"),recoveryEmailChanged:Object.prototype.hasOwnProperty.call(input||{},"recoveryEmail")}});return result;};
  if(prop==="sendPrivateMessage")return async(userId,input)=>{await moderation.enforce({userId,context:"message",value:input?.subject});await moderation.enforce({userId,context:"message",value:input?.body});const result=await target.sendPrivateMessage(userId,input);await moderation.audit?.record({actorId:userId,eventType:"private-message.sent",targetType:"message",targetId:result?.messageId||null,metadata:{recipientId:input?.recipientId||null}});return result;};
  if(prop==="deletePrivateMessage")return async(userId,messageId)=>{const result=await target.deletePrivateMessage(userId,messageId);await moderation.audit?.record({actorId:userId,eventType:"private-message.deleted",targetType:"message",targetId:messageId});return result;};
  return original.bind(target);
}});}
export function withChatModeration(service,moderation){return new Proxy(service,{get(target,prop){const original=target[prop];if(prop==="send")return async(user,input)=>{await moderation.enforce({userId:user.userId,context:"chat",value:input?.body});return target.send(user,input);};if(prop==="createTopic")return async(user,input)=>{await moderation.enforce({userId:user.userId,context:"chat",value:`${input?.title||""} ${input?.description||""}`});return target.createTopic(user,input);};return typeof original==="function"?original.bind(target):original;}});}
