#!/usr/bin/env bash
set -euo pipefail
: "${DATABASE_URL:?DATABASE_URL required}";: "${AUTH_SECRET:?AUTH_SECRET required}"
REPLICAS="${WAVE_B_REPLICAS:-1}";VUS="${WAVE_B_VUS:-100}";SCENARIO="${WAVE_B_SCENARIO:-mixed-platform}";RUN_ID="${WAVE_B_RUN_ID:-b1-r${REPLICAS}-v${VUS}-${SCENARIO}}";BASE_PORT="${WAVE_B_BASE_PORT:-3000}";REPORT_DIR="perf/k6/reports";PIDS_FILE="/tmp/wave-b-app-pids-${RUN_ID}";WARMUP_SECONDS="${WAVE_B_WARMUP_SECONDS:-120}";STEADY_SECONDS="${WAVE_B_STEADY_SECONDS:-300}";COOLDOWN_SECONDS="${WAVE_B_COOLDOWN_SECONDS:-120}";TOTAL_SECONDS=$((WARMUP_SECONDS+STEADY_SECONDS+COOLDOWN_SECONDS+15));mkdir -p "$REPORT_DIR";:>"$PIDS_FILE";export WAVE_B_RUN_ID="$RUN_ID" WAVE_B_REPLICAS="$REPLICAS" WAVE_B_VUS="$VUS" WAVE_B_WARMUP_SECONDS="$WARMUP_SECONDS" WAVE_B_STEADY_SECONDS="$STEADY_SECONDS" WAVE_B_COOLDOWN_SECONDS="$COOLDOWN_SECONDS";node perf/scripts/wave-b-preflight.mjs
pids=();ports=();cleanup(){ for pid in "${pids[@]:-}";do kill "$pid" 2>/dev/null||true;done;for pid in "${pids[@]:-}";do wait "$pid" 2>/dev/null||true;done;};trap cleanup EXIT
for ((i=0;i<REPLICAS;i++));do port=$((BASE_PORT+i));ports+=("$port");obs="$REPORT_DIR/${RUN_ID}-observability-${i}.jsonl";PORT="$port" HOST=127.0.0.1 NODE_ENV=test WAVE_B_OBS_FILE="$obs" node --require ./perf/scripts/wave-b-observability-preload.cjs --require ./src/pg-secure-preload.cjs src/main.js >"$REPORT_DIR/${RUN_ID}-app-${i}.log" 2>&1 & pid=$!;pids+=("$pid");echo "$pid">>"$PIDS_FILE";done
for port in "${ports[@]}";do ok=0;for _ in $(seq 1 180);do if curl -fsS "http://127.0.0.1:${port}/health/ready" >/dev/null;then ok=1;break;fi;sleep .5;done;if [[ "$ok" != 1 ]];then echo "Replica on $port failed readiness" >&2;tail -120 "$REPORT_DIR/${RUN_ID}-app-"*.log >&2||true;exit 20;fi;done
BASE_URLS=$(printf 'http://127.0.0.1:%s,' "${ports[@]}");BASE_URLS=${BASE_URLS%,};export BASE_URLS;USER_COUNT="${WAVE_B_USER_COUNT:-$((VUS+700))}";if((USER_COUNT<1600));then USER_COUNT=1600;fi;WAVE_B_USER_COUNT="$USER_COUNT" WAVE_B_GAME_COUNT="${WAVE_B_GAME_COUNT:-50}" node perf/scripts/wave-b-seed.mjs;bash perf/scripts/wave-b-env-snapshot.sh;node perf/scripts/wave-b-listener-headroom.mjs||true
WAVE_B_PG_SAMPLE_SECONDS="$TOTAL_SECONDS" bash perf/scripts/wave-b-postgres-sample.sh & pg_sampler=$!;WAVE_B_PIDS_FILE="$PIDS_FILE" WAVE_B_APP_PORTS="$(IFS=,;echo "${ports[*]}")" WAVE_B_APP_SAMPLE_SECONDS="$TOTAL_SECONDS" bash perf/scripts/wave-b-app-sample.sh & app_sampler=$!;WAVE_B_PROBE_DELAY_SECONDS=$((WARMUP_SECONDS+5)) node perf/scripts/wave-b-correctness-probe.mjs >"$REPORT_DIR/${RUN_ID}-correctness-probe.log" 2>&1 & probe_pid=$!
set +e;WAVE_B_SCENARIO="$SCENARIO" k6 run "perf/k6/scenarios/${WAVE_B_SCENARIO_FILE:-10-mixed-platform.js}" --summary-export "$REPORT_DIR/${RUN_ID}-k6-summary-export.json";k6_status=$?;wait "$probe_pid";probe_status=$?;wait "$pg_sampler";pg_status=$?;wait "$app_sampler";app_status=$?;WAVE_B_SUMMARY="$REPORT_DIR/${RUN_ID}-k6-summary-export.json" node perf/scripts/wave-b-correctness-check.mjs;correctness_status=$?;set -e
psql "$DATABASE_URL" -At -F',' -c "SELECT now(),count(*) FILTER(WHERE state='active'),count(*) FILTER(WHERE state='idle'),count(*) FILTER(WHERE wait_event IS NOT NULL) FROM pg_stat_activity WHERE datname=current_database();">"$REPORT_DIR/${RUN_ID}-pg-final.txt"||true;printf '{"runId":"%s","head":"%s","tree":"%s","replicas":%s,"vus":%s,"scenario":"%s","baseUrls":"%s","warmupSeconds":%s,"steadySeconds":%s,"cooldownSeconds":%s,"k6Exit":%s,"probeExit":%s,"correctnessExit":%s,"pgSamplerExit":%s,"appSamplerExit":%s}\n' "$RUN_ID" "$(git rev-parse HEAD)" "$(git rev-parse HEAD^{tree})" "$REPLICAS" "$VUS" "$SCENARIO" "$BASE_URLS" "$WARMUP_SECONDS" "$STEADY_SECONDS" "$COOLDOWN_SECONDS" "$k6_status" "$probe_status" "$correctness_status" "$pg_status" "$app_status">"$REPORT_DIR/${RUN_ID}-record.json";if((k6_status!=0));then exit "$k6_status";fi;if((probe_status!=0||correctness_status!=0||pg_status!=0||app_status!=0));then exit 2;fi
