import {createHash} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import pg from 'pg';
import {AuthService} from '../../src/auth.js';
const {Pool}=pg;const secret=process.env.AUTH_SECRET;if(!secret||Buffer.byteLength(secret)<32)throw new Error('AUTH_SECRET >= 32 bytes is required.');const url=process.env.DATABASE_URL;if(!url)throw new Error('DATABASE_URL required');
const baseUrls=String(process.env.BASE_URLS||'http://127.0.0.1:3000').split(',').map(x=>x.trim()).filter(Boolean),base=baseUrls[0];
const userCount=Math.max(100,Math.min(200000,Number(process.env.WAVE_B_USER_COUNT||1600))),gameCount=Math.max(1,Math.min(10000,Number(process.env.WAVE_B_GAME_COUNT||50))),runId=String(process.env.WAVE_B_RUN_ID||'waveb').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,32)||'waveb',output=resolve(process.env.WAVE_B_DATASET||'perf/k6/datasets/runtime.json');
const auth=new AuthService({secret,ttlSeconds:7200});const users=Array.from({length:userCount},(_,i)=>{const n=String(i+1).padStart(6,'0');const userId=`wb${n}`;return{userId,displayName:`WB ${n}`,token:auth.issueGuest({userId,displayName:`WB ${n}`,ttlSeconds:7200})}});let cursor=0;function take(count){if(cursor+count>users.length)throw new Error(`Need more users: ${cursor}+${count}>${users.length}`);const x=users.slice(cursor,cursor+count);cursor+=count;return x}
async function api(path,{method='GET',body,user}={}){const response=await fetch(`${base}${path}`,{method,headers:{accept:'application/json',...(body?{'content-type':'application/json'}:{}),...(user?{authorization:`Bearer ${user.token}`}:{})},body:body?JSON.stringify(body):undefined});const text=await response.text();let payload={};try{payload=text?JSON.parse(text):{}}catch{payload={raw:text.slice(0,500)}}if(!response.ok)throw new Error(`${method} ${path} => ${response.status} ${JSON.stringify(payload).slice(0,800)}`);return payload}
async function seedLobbyGame(gameType,playerCount){const players=take(playerCount),owner=players[0];const room=await api('/lobby/rooms',{method:'POST',user:owner,body:{roomName:`${runId}-${gameType}-${cursor}`,gameType,maxPlayers:playerCount}});let current=room;for(const player of players.slice(1))current=await api(`/lobby/rooms/${encodeURIComponent(room.roomId)}/join`,{method:'POST',user:player,body:{}});if(!current.gameId||current.status!=='playing')throw new Error(`Seeded ${gameType} room did not become playing`);return{gameId:current.gameId,roomId:current.roomId,players:players.map(p=>p.userId)}}
await api('/health');const checkersGames=[],gomokuGames=[],thousandGames=[];for(let i=0;i<gameCount;i++)checkersGames.push(await seedLobbyGame('checkers',2));for(let i=0;i<gameCount;i++)gomokuGames.push(await seedLobbyGame('gomoku',2));for(let i=0;i<gameCount;i++)thousandGames.push(await seedLobbyGame('thousand',3));
const pool=new Pool({connectionString:url,max:2});async function versions(table,column,games){if(!games.length)return;const ids=games.map(g=>g.gameId);const {rows}=await pool.query(`SELECT game_id,${column} AS revision FROM ${table} WHERE game_id=ANY($1)`,[ids]);const map=new Map(rows.map(r=>[r.game_id,Number(r.revision)]));for(const game of games)game[column==='version'?'initialVersion':'initialRevision']=map.get(game.gameId)??null}
await versions('gracz_game_sessions','version',checkersGames);await versions('gracz_gomoku_games','revision',gomokuGames);await versions('gracz_thousand_games','revision',thousandGames);await pool.end();
const structural={runId,seed:process.env.WAVE_B_SEED||'20260909',users:users.map(u=>u.userId),checkersGames,gomokuGames,thousandGames};const datasetId=createHash('sha256').update(JSON.stringify(structural)).digest('hex');const data={runId,datasetId,baseUrls,seed:structural.seed,generatedAt:new Date().toISOString(),users,checkersGames,gomokuGames,thousandGames};await mkdir(dirname(output),{recursive:true});await writeFile(output,JSON.stringify(data));console.log(JSON.stringify({runId,output,datasetId,userCount:users.length,checkersGames:checkersGames.length,gomokuGames:gomokuGames.length,thousandGames:thousandGames.length},null,2));
