name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey! Welcome on board and thank You for Your first commit!'
        pr-message: 'Great! Thank You for Your first PullRequest for our gaming platform.'
