const AVATAR_KEY = "gracz-avatar-v1";

const avatars = [
  ["strateg","Strateg","♟","Strategia","emerald"],["king","Król","♔","Strategia","gold"],["queen","Królowa","♕","Strategia","violet"],["rook","Wieża","♜","Strategia","steel"],["bishop","Goniec","♝","Strategia","blue"],["knightpiece","Skoczek","♞","Strategia","cyan"],["checker","Warcabista","⛀","Strategia","red"],["checkerking","Dama","⛁","Strategia","gold"],
  ["crown","Mistrz","👑","Elita","gold"],["trophy","Puchar","🏆","Elita","gold"],["medal","Medalista","🥇","Elita","gold"],["diamond","Diament","💎","Elita","cyan"],["star","Gwiazda","★","Elita","violet"],["champion","Champion","🏅","Elita","amber"],["legend","Legenda","🌟","Elita","gold"],["ace","As","🂡","Elita","red"],
  ["controller","Gamer","🎮","Gaming","emerald"],["joystick","Joystick","🕹️","Gaming","violet"],["pixel","Pixel","👾","Gaming","violet"],["ghost","Duch","👻","Gaming","cyan"],["alien","Kosmita","👽","Gaming","emerald"],["robot","Robot","🤖","Gaming","cyan"],["rocket","Rakieta","🚀","Gaming","blue"],["target","Snajper","🎯","Gaming","red"],["bolt","Błyskawica","⚡","Gaming","amber"],["fire","Ogień","🔥","Gaming","orange"],["bomb","Bomba","💣","Gaming","slate"],["dice","Kości","🎲","Gaming","red"],["cards","Karty","🃏","Gaming","violet"],["arcade","Arcade","🎰","Gaming","gold"],["headset","Headset","🎧","Gaming","blue"],["keyboard","Klawiatura","⌨️","Gaming","steel"],
  ["ninja","Ninja","🥷","Bohaterowie","slate"],["warrior","Wojownik","⚔️","Bohaterowie","red"],["shield","Obrońca","🛡️","Bohaterowie","steel"],["mage","Mag","🧙","Bohaterowie","violet"],["wizard","Czarodziej","🪄","Bohaterowie","violet"],["detective","Detektyw","🕵️","Bohaterowie","slate"],["pirate","Pirat","🏴‍☠️","Bohaterowie","red"],["samurai","Samuraj","🥷","Bohaterowie","red"],["hero","Supergracz","🦸","Bohaterowie","blue"],["cyborg","Cyborg","🦾","Bohaterowie","cyan"],["astronaut","Astronauta","🧑‍🚀","Bohaterowie","blue"],["viking","Wiking","🪓","Bohaterowie","amber"],
  ["wolf","Wilk","🐺","Zwierzęta","steel"],["tiger","Tygrys","🐯","Zwierzęta","orange"],["lion","Lew","🦁","Zwierzęta","gold"],["fox","Lis","🦊","Zwierzęta","orange"],["eagle","Orzeł","🦅","Zwierzęta","blue"],["owl","Sowa","🦉","Zwierzęta","violet"],["bear","Niedźwiedź","🐻","Zwierzęta","amber"],["panther","Pantera","🐈‍⬛","Zwierzęta","slate"],["shark","Rekin","🦈","Zwierzęta","blue"],["cobra","Kobra","🐍","Zwierzęta","emerald"],["falcon","Sokół","🦅","Zwierzęta","steel"],["bull","Byk","🐂","Zwierzęta","red"],["ram","Baran","🐏","Zwierzęta","steel"],["raven","Kruk","🐦‍⬛","Zwierzęta","slate"],["cat","Kot","🐱","Zwierzęta","violet"],["dog","Pies","🐶","Zwierzęta","amber"],
  ["dragon","Smok","🐉","Fantasy","red"],["phoenix","Feniks","🔥","Fantasy","amber"],["unicorn","Jednorożec","🦄","Fantasy","violet"],["skull","Czaszka","💀","Fantasy","slate"],["demon","Demon","😈","Fantasy","red"],["angel","Anioł","😇","Fantasy","cyan"],["moon","Księżyc","🌙","Fantasy","blue"],["sun","Słońce","☀️","Fantasy","gold"],["comet","Kometa","☄️","Fantasy","orange"],["planet","Planeta","🪐","Fantasy","violet"],["crystal","Kryształ","🔮","Fantasy","violet"],["snow","Lód","❄️","Fantasy","cyan"],
  ["smile","Uśmiech","😎","Klasyczne","blue"],["cool","Cool","😏","Klasyczne","emerald"],["brain","Mózg","🧠","Klasyczne","violet"],["lightbulb","Pomysł","💡","Klasyczne","amber"],["coffee","Kawa","☕","Klasyczne","amber"],["music","Muzyka","🎵","Klasyczne","violet"],["heart","Serce","❤️","Klasyczne","red"],["clover","Szczęście","🍀","Klasyczne","emerald"],["mountain","Szczyt","⛰️","Klasyczne","steel"],["wave","Fala","🌊","Klasyczne","blue"],["tree","Drzewo","🌲","Klasyczne","emerald"],["globe","Świat","🌍","Klasyczne","blue"]
];

const colors={emerald:["#1ef18c","#073c2b"],gold:["#ffd15a","#573706"],violet:["#b487ff","#321763"],steel:["#b2c5cf","#26343e"],red:["#ff6673","#59151d"],amber:["#ffc568","#5c3507"],orange:["#ff914f","#62250c"],blue:["#5aadff","#12385f"],slate:["#c1cbd3","#202c38"],cyan:["#45eee7","#0a4d50"]};
let selected=localStorage.getItem(AVATAR_KEY)||"strateg";

function data(id){return avatars.find(a=>a[0]===id)||avatars[0]}
function paint(node,id=selected){if(!node)return;const a=data(id),c=colors[a[4]]||colors.emerald;node.textContent=a[2];node.dataset.avatar=id;node.style.background=`radial-gradient(circle at 32% 22%,${c[0]}55 0,transparent 36%),linear-gradient(145deg,${c[1]},#071117)`;node.style.borderColor=c[0]+"99";node.style.color="#fff";node.title=`Avatar: ${a[1]}`}

function addStyles(){const s=document.createElement("style");s.textContent=`
.avatar{font-size:32px!important;overflow:hidden;box-shadow:inset 0 0 24px #0006,0 0 0 3px #0b171f,0 0 0 4px #23424b}.avatar-picker{width:min(980px,95vw);max-height:90vh;padding:0;border:1px solid #28505b;border-radius:18px;background:linear-gradient(180deg,#0d1c24,#081319);color:#eef7f2;box-shadow:0 30px 100px #000c;overflow:hidden}.avatar-picker::backdrop{background:#02070be6;backdrop-filter:blur(8px)}.av-head{display:flex;justify-content:space-between;gap:20px;padding:22px 24px;border-bottom:1px solid #19343d;background:#0a171e}.av-head h2{margin:0;font-size:23px}.av-head p{margin:5px 0 0;color:#7e9892;font-size:12px}.av-close{border:0;background:transparent;color:#90a59f;font-size:28px;cursor:pointer}.av-tabs{display:flex;gap:8px;overflow:auto;padding:15px 24px 5px}.av-tabs button{border:1px solid #29464f;border-radius:999px;background:#0c1c23;color:#91a9a3;padding:8px 12px;cursor:pointer;white-space:nowrap}.av-tabs button.active{border-color:#20c977;background:#0b3522;color:#5de9a0}.av-body{padding:17px 24px 24px;overflow:auto;max-height:60vh}.av-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(126px,1fr));gap:11px}.av-item{position:relative;display:grid;place-items:center;gap:7px;min-height:142px;padding:13px 8px;border:1px solid #1d3942;border-radius:13px;background:linear-gradient(180deg,#0d1b22,#09141a);color:#dce9e4;cursor:pointer;transition:.16s}.av-item:hover{border-color:#3d6872;transform:translateY(-2px);background:#10232a}.av-item.selected{border-color:#24dc7d;box-shadow:0 0 0 2px #20df7830,inset 0 0 28px #0f8d4f16}.av-item.selected:after{content:'✓';position:absolute;right:8px;top:8px;width:21px;height:21px;display:grid;place-items:center;border-radius:50%;background:#20df78;color:#06210f;font-weight:900}.av-preview{width:70px;height:70px;display:grid;place-items:center;border:1px solid #3f6975;border-radius:20px;font-size:34px;box-shadow:inset 0 0 22px #0005}.av-item strong{font-size:11px}.av-item small{color:#708a84;font-size:9px;text-align:center}.av-foot{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:15px 24px;border-top:1px solid #19343d;background:#09161c}.av-current{display:flex;align-items:center;gap:10px;color:#8ba09b;font-size:11px}.av-mini{width:40px;height:40px;display:grid;place-items:center;border-radius:11px;font-size:21px}.av-save{border:0;border-radius:9px;padding:10px 18px;background:linear-gradient(#28e987,#10b95d);color:#042011;font-weight:900;cursor:pointer}@media(max-width:600px){.av-grid{grid-template-columns:repeat(2,1fr)}.av-head,.av-tabs,.av-body,.av-foot{padding-left:14px;padding-right:14px}.av-foot{align-items:stretch;flex-direction:column}.av-save{width:100%}}
`;document.head.append(s)}

function ensureDialog(){let d=document.querySelector("#avatar-picker");if(d)return d;d=document.createElement("dialog");d.id="avatar-picker";d.className="avatar-picker";const cats=["Wszystkie",...new Set(avatars.map(a=>a[3]))];d.innerHTML=`<div class="av-head"><div><h2>Biblioteka avatarów Gracz.pl</h2><p>Wybierz avatar, który najlepiej pasuje do Twojego stylu gry.</p></div><button class="av-close" type="button">×</button></div><div class="av-tabs"></div><div class="av-body"><div class="av-grid"></div></div><div class="av-foot"><div class="av-current"><span class="av-mini"></span><span class="av-label"></span></div><button class="av-save" type="button">Ustaw wybrany avatar</button></div>`;document.body.append(d);const tabs=d.querySelector(".av-tabs");cats.forEach((cat,i)=>{const b=document.createElement("button");b.type="button";b.textContent=cat;b.classList.toggle("active",i===0);b.addEventListener("click",()=>{tabs.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));render(cat)});tabs.append(b)});d.querySelector(".av-close").addEventListener("click",()=>d.close());d.addEventListener("click",e=>{if(e.target===d)d.close()});d.querySelector(".av-save").addEventListener("click",()=>{localStorage.setItem(AVATAR_KEY,selected);paint(document.querySelector("#avatar"));d.close();const t=document.querySelector("#toast");if(t){t.textContent=`Avatar „${data(selected)[1]}” został ustawiony.`;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)}});return d}
function render(category="Wszystkie"){const d=ensureDialog(),grid=d.querySelector(".av-grid");grid.replaceChildren();avatars.filter(a=>category==="Wszystkie"||a[3]===category).forEach(a=>{const c=colors[a[4]]||colors.emerald,b=document.createElement("button");b.type="button";b.className=`av-item${a[0]===selected?" selected":""}`;b.innerHTML=`<span class="av-preview"></span><strong></strong><small></small>`;const p=b.querySelector(".av-preview");p.textContent=a[2];p.style.background=`radial-gradient(circle at 32% 22%,${c[0]}55 0,transparent 36%),linear-gradient(145deg,${c[1]},#071117)`;p.style.borderColor=c[0]+"99";b.querySelector("strong").textContent=a[1];b.querySelector("small").textContent=a[3];b.addEventListener("click",()=>{selected=a[0];render(category)});grid.append(b)});const a=data(selected),c=colors[a[4]]||colors.emerald,m=d.querySelector(".av-mini");m.textContent=a[2];m.style.background=`linear-gradient(145deg,${c[1]},#071117)`;m.style.border=`1px solid ${c[0]}99`;d.querySelector(".av-label").textContent=`Wybrano: ${a[1]}`}

function init(){addStyles();paint(document.querySelector("#avatar"));const btn=[...document.querySelectorAll(".profile-card button")].find(b=>/avatar/i.test(b.textContent));if(!btn)return;btn.removeAttribute("data-toast");btn.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();render("Wszystkie");ensureDialog().showModal()},true);new MutationObserver(()=>paint(document.querySelector("#avatar"))).observe(document.querySelector("#profile-name")||document.body,{childList:true,subtree:true})}

if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
