const state={me:null,online:[],friends:[],topics:[],view:'feed',query:''};
const $=(s)=>document.querySelector(s);
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',headers:{accept:'application/json',...(options.headers||{})},...options});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error?.message||`Błąd ${r.status}`);return b}
function initials(name){return String(name||'?').trim().slice(0,2).toUpperCase()}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setView(view){state.view=view;document.querySelectorAll('.side-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));const meta={feed:['Społeczność','Poznawaj graczy, obserwuj aktywność i buduj swoją sieć znajomych.'],players:['Gracze','Wyszukaj użytkowników i nawiąż nowe kontakty.'],friends:['Znajomi','Zarządzaj swoją siecią znajomych na Gracz.pl.'],requests:['Zaproszenia','Obsługuj oczekujące zaproszenia do znajomych.'],clubs:['Kluby i grupy','Buduj społeczności wokół gier, drużyn i turniejów.'],events:['Wydarzenia','Przeglądaj wydarzenia i aktywności społeczności.']}[view];$('#view-title').textContent=meta[0];$('#view-subtitle').textContent=meta[1];if(view==='players')searchPlayers(state.query);if(view==='friends'||view==='requests')renderFriends();window.scrollTo({top:0,behavior:'smooth'})}
async function loadIdentity(){const r=await api('/auth/me');state.me=r.user;$('#identity').textContent=`${r.user.displayName} (@${r.user.userId})`;$('#me-name').textContent=r.user.displayName;$('#me-id').textContent=`@${r.user.userId}`;$('#me-avatar').textContent=initials(r.user.displayName)}
async function loadCommunity(){const [chat,topics,friends]=await Promise.allSettled([api('/global-chat/messages?limit=20'),api('/global-chat/topics'),api('/global-chat/friends')]);if(chat.status==='fulfilled')state.online=chat.value.online||[];if(topics.status==='fulfilled')state.topics=topics.value.topics||topics.value||[];if(friends.status==='fulfilled')state.friends=friends.value.friends||friends.value||[];renderAll()}
function acceptedFriends(){return state.friends.filter(f=>f.status==='accepted')}
function incoming(){return state.friends.filter(f=>f.status==='pending'&&f.addresseeId===state.me?.userId)}
function renderStats(){$('#stat-online').textContent=state.online.length;$('#stat-friends').textContent=acceptedFriends().length;$('#stat-requests').textContent=incoming().length;$('#stat-topics').textContent=state.topics.length;$('#friend-count').textContent=acceptedFriends().length;$('#request-count').textContent=incoming().length}
function renderOnline(){const root=$('#online-list');root.replaceChildren();const list=state.online.filter(p=>p.userId!==state.me?.userId).slice(0,8);if(!list.length){root.innerHTML='<div class="empty">Brak innych graczy online.</div>';return}for(const p of list){const row=document.createElement('div');row.className='person-row';row.innerHTML=`<div class="avatar">${escapeHtml(initials(p.displayName))}</div><div class="person-main"><b>${escapeHtml(p.displayName)}</b><p>@${escapeHtml(p.userId)}</p></div><i class="online-dot"></i>`;root.append(row)}}
function renderTopics(){const root=$('#topic-list');root.replaceChildren();const list=state.topics.slice(0,6);if(!list.length){root.innerHTML='<div class="empty">Nie ma jeszcze tematów.</div>';return}for(const t of list){const row=document.createElement('div');row.className='topic-row';row.innerHTML=`<div><b>${escapeHtml(t.title)}</b><p>${escapeHtml(t.category||'ogólne')} · ${escapeHtml(t.ownerName||'Gracz')}</p></div><small>${Number(t.messageCount||0)} wpisów</small>`;row.addEventListener('click',()=>location.href='/global-chat.html');root.append(row)}}
function renderFeed(){const root=$('#feed-list');root.replaceChildren();const items=[...state.topics.slice(0,5).map(t=>({name:t.ownerName||'Gracz',text:`utworzył temat „${t.title}”`,meta:t.category||'ogólne'})),...state.online.slice(0,5).map(p=>({name:p.displayName,text:'jest teraz online',meta:'aktywny gracz'}))].slice(0,8);if(!items.length){root.innerHTML='<div class="empty">Aktywność pojawi się, gdy gracze zaczną korzystać ze społeczności.</div>';return}for(const i of items){const row=document.createElement('div');row.className='feed-item';row.innerHTML=`<div class="avatar">${escapeHtml(initials(i.name))}</div><div class="feed-main"><b>${escapeHtml(i.name)}</b><p>${escapeHtml(i.text)}</p></div><small>${escapeHtml(i.meta)}</small>`;root.append(row)}}
function relationFor(userId){return state.friends.find(f=>(f.requesterId===state.me?.userId&&f.addresseeId===userId)||(f.addresseeId===state.me?.userId&&f.requesterId===userId))}
function personCard(p){const rel=relationFor(p.userId);const el=document.createElement('article');el.className='person-card';let action='Dodaj znajomego',disabled=false;if(rel?.status==='accepted'){action='Znajomy';disabled=true}else if(rel?.status==='pending'){action='Zaproszenie wysłane';disabled=true}el.innerHTML=`<header><div class="avatar">${escapeHtml(initials(p.displayName))}</div><div><h3>${escapeHtml(p.displayName)}</h3><p>@${escapeHtml(p.userId)}</p></div></header><p>Gracz społeczności Gracz.pl</p><div class="actions"><button class="primary" ${disabled?'disabled':''}>${action}</button><a href="/messages.html">Wiadomość</a></div>`;const btn=el.querySelector('button');if(!disabled)btn.addEventListener('click',async()=>{try{await api('/global-chat/friends',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:p.userId,displayName:p.displayName})});toast('Zaproszenie zostało wysłane.');await loadCommunity()}catch(e){toast(e.message)}});return el}
async function searchPlayers(q=''){const root=$('#player-results');root.innerHTML='<div class="empty">Wyszukiwanie…</div>';try{const r=await api(`/players/search?q=${encodeURIComponent(q)}`);root.replaceChildren();const players=(r.players||[]).filter(p=>p.userId!==state.me?.userId);if(!players.length){root.innerHTML='<div class="empty">Nie znaleziono graczy.</div>';return}players.forEach(p=>root.append(personCard(p)))}catch(e){root.innerHTML=`<div class="empty">${escapeHtml(e.message)}</div>`}}
function renderFriends(){const friendsRoot=$('#friends-list'),requestsRoot=$('#requests-list');friendsRoot.replaceChildren();requestsRoot.replaceChildren();const accepted=acceptedFriends(),reqs=incoming();if(!accepted.length)friendsRoot.innerHTML='<div class="empty">Nie masz jeszcze znajomych. Użyj wyszukiwarki graczy.</div>';for(const f of accepted){const other=f.requesterId===state.me.userId?{userId:f.addresseeId,displayName:f.addresseeName}:{userId:f.requesterId,displayName:f.requesterName};const card=personCard(other);card.querySelector('button').remove();friendsRoot.append(card)}if(!reqs.length)requestsRoot.innerHTML='<div class="empty">Brak oczekujących zaproszeń.</div>';for(const f of reqs){const card=document.createElement('article');card.className='person-card';card.innerHTML=`<header><div class="avatar">${escapeHtml(initials(f.requesterName))}</div><div><h3>${escapeHtml(f.requesterName)}</h3><p>@${escapeHtml(f.requesterId)}</p></div></header><p>Chce dodać Cię do znajomych.</p><div class="actions"><button class="primary">Akceptuj</button><button>Odrzuć</button></div>`;const [yes,no]=card.querySelectorAll('button');yes.addEventListener('click',()=>respondFriend(f.relationId,'accept'));no.addEventListener('click',()=>respondFriend(f.relationId,'reject'));requestsRoot.append(card)}}
async function respondFriend(id,action){try{await api(`/global-chat/friends/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action})});toast(action==='accept'?'Dodano do znajomych.':'Zaproszenie odrzucone.');await loadCommunity()}catch(e){toast(e.message)}}
function renderAll(){renderStats();renderOnline();renderTopics();renderFeed();renderFriends()}
function bind(){document.querySelectorAll('.side-nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-view-jump]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.viewJump)));$('#global-search').addEventListener('input',e=>state.query=e.target.value.trim());$('#global-search').addEventListener('keydown',e=>{if(e.key==='Enter'){setView('players');searchPlayers(state.query)}});$('#find-player').addEventListener('click',()=>{setView('players');$('#global-search').focus()});$('#refresh-feed').addEventListener('click',loadCommunity);$('#club-info').addEventListener('click',()=>toast('Kluby są przygotowane jako kolejny etap rozbudowy społeczności.'))}
async function init(){try{await loadIdentity();bind();await loadCommunity()}catch(e){toast(e.message);setTimeout(()=>location.href='/',1200)}}
init();
