const state={me:null,messages:new Map(),order:[],online:[],replyTo:null,eventSource:null,sound:true,stickToBottom:true};
const $=(s)=>document.querySelector(s);
const list=$("#message-list"),input=$("#message-input"),form=$("#chat-form"),send=$("#send-button");
const EMOJIS=["😀","😃","😄","😁","😂","🤣","😊","😎","😍","🤩","😉","🙂","🙃","😅","🥳","🤔","😮","😲","😴","😡","🤝","👍","👎","👏","🙌","💪","🔥","❤️","💚","💙","🎮","🏆","🥇","🎯","⚡","♟️","♞","♛","⛀","⛁","🎲","🃏","🚀","👑","🐺","🐯","🦁","🐉","🦅","🍀","☕"];
const AVATAR_KEY="gracz-avatar-v1";
const AVATARS={strateg:"♟",king:"♔",queen:"♕",rook:"♜",bishop:"♝",knightpiece:"♞",checker:"⛀",checkerking:"⛁",crown:"👑",trophy:"🏆",medal:"🥇",diamond:"💎",star:"★",champion:"🏅",legend:"🌟",ace:"🂡",controller:"🎮",joystick:"🕹️",pixel:"👾",ghost:"👻",alien:"👽",robot:"🤖",rocket:"🚀",target:"🎯",bolt:"⚡",fire:"🔥",bomb:"💣",dice:"🎲",cards:"🃏",arcade:"🎰",headset:"🎧",keyboard:"⌨️",ninja:"🥷",warrior:"⚔️",shield:"🛡️",mage:"🧙",wizard:"🪄",detective:"🕵️",pirate:"🏴‍☠️",samurai:"🥷",hero:"🦸",cyborg:"🦾",astronaut:"🧑‍🚀",viking:"🪓",wolf:"🐺",tiger:"🐯",lion:"🦁",fox:"🦊",eagle:"🦅",owl:"🦉",bear:"🐻",panther:"🐈‍⬛",shark:"🦈",cobra:"🐍",falcon:"🦅",bull:"🐂",ram:"🐏",raven:"🐦‍⬛",cat:"🐱",dog:"🐶",dragon:"🐉",phoenix:"🔥",unicorn:"🦄",skull:"💀",demon:"😈",angel:"😇",moon:"🌙",sun:"☀️",comet:"☄️",planet:"🪐",crystal:"🔮",snow:"❄️",smile:"😎",cool:"😏",brain:"🧠",lightbulb:"💡",coffee:"☕",music:"🎵",heart:"❤️",clover:"🍀",mountain:"⛰️",wave:"🌊",tree:"🌲",globe:"🌍"};
function myAvatar(){return AVATARS[localStorage.getItem(AVATAR_KEY)||"strateg"]||"🎮"}
function avatarFor(msg){if(msg.userId===state.me?.userId)return myAvatar();const chars=["♟","♞","⛀","🎮","🏆","🎯","⚡","🐺","🐉","🦅","💎","👑"];let n=0;for(const c of msg.userId)n=(n*31+c.charCodeAt(0))>>>0;return chars[n%chars.length]}
function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),3000)}
async function api(path,options={}){const r=await fetch(path,{credentials:"same-origin",headers:{accept:"application/json",...(options.headers||{})},...options});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error?.message||`Błąd ${r.status}`);return b}
async function loadIdentity(){try{const r=await api("/auth/me");state.me=r.user;$("#identity").textContent=`${r.user.displayName} (@${r.user.userId})`}catch{location.replace("/")}}
function setPresence(users=[]){state.online=users;$("#online-count").textContent=String(users.length);const root=$("#online-list");root.replaceChildren();if(!users.length){const e=document.createElement("div");e.className="online-user";e.textContent="Brak aktywnych graczy";root.append(e);return}users.forEach(u=>{const row=document.createElement("div");row.className="online-user";const dot=document.createElement("i");dot.className="user-dot";const box=document.createElement("div");const b=document.createElement("b");b.textContent=u.displayName;const s=document.createElement("small");s.textContent=`@${u.userId}`;box.append(b,s);row.append(dot,box);root.append(row)})}
function formatTime(value){const d=new Date(value);return new Intl.DateTimeFormat("pl-PL",{hour:"2-digit",minute:"2-digit"}).format(d)}
function reactionCounts(reactions={}){return Object.entries(reactions).filter(([,users])=>Array.isArray(users)&&users.length)}
function findMessage(id){return id?state.messages.get(id):null}
function messageNode(msg){const article=document.createElement("article");article.className=`message${msg.userId===state.me?.userId?" mine":""}${msg.deleted?" deleted":""}`;article.dataset.id=msg.messageId;const av=document.createElement("div");av.className="message-avatar";av.textContent=avatarFor(msg);const main=document.createElement("div");const head=document.createElement("div");head.className="message-head";const name=document.createElement("span");name.className="message-name";name.textContent=msg.displayName;const time=document.createElement("span");time.className="message-time";time.textContent=formatTime(msg.createdAt);head.append(name,time);if(msg.editedAt){const ed=document.createElement("span");ed.className="edited";ed.textContent="edytowano";head.append(ed)}main.append(head);if(msg.replyTo){const r=findMessage(msg.replyTo);const rp=document.createElement("div");rp.className="reply-preview";rp.textContent=r&&!r.deleted?`↪ ${r.displayName}: ${r.body.slice(0,90)}`:"↪ Odpowiedź na wcześniejszą wiadomość";main.append(rp)}const body=document.createElement("div");body.className="message-body";body.textContent=msg.deleted?"Wiadomość usunięta przez autora.":msg.body;main.append(body);if(!msg.deleted){const actions=document.createElement("div");actions.className="message-actions";const reply=document.createElement("button");reply.type="button";reply.textContent="Odpowiedz";reply.addEventListener("click",()=>startReply(msg));actions.append(reply);reactionCounts(msg.reactions).forEach(([emoji,users])=>{const b=document.createElement("button");b.type="button";b.className=`reaction-pill${users.includes(state.me?.userId)?" active":""}`;b.textContent=`${emoji} ${users.length}`;b.addEventListener("click",()=>react(msg.messageId,emoji));actions.append(b)});const reactBtn=document.createElement("button");reactBtn.type="button";reactBtn.textContent="＋ reakcja";reactBtn.addEventListener("click",e=>openReactionMenu(e,msg));actions.append(reactBtn);const more=document.createElement("button");more.type="button";more.textContent="•••";more.addEventListener("click",e=>openContextMenu(e,msg));actions.append(more);main.append(actions)}article.append(av,main);return article}
function renderAll(forceBottom=false){const wasBottom=isNearBottom();list.replaceChildren();for(const id of state.order){const msg=state.messages.get(id);if(msg)list.append(messageNode(msg))}if(forceBottom||wasBottom||state.stickToBottom)requestAnimationFrame(()=>list.scrollTop=list.scrollHeight)}
function upsert(msg){const exists=state.messages.has(msg.messageId);state.messages.set(msg.messageId,msg);if(!exists)state.order.push(msg.messageId);if(state.order.length>180){const old=state.order.shift();state.messages.delete(old)}renderAll(false)}
function removeMessage(id){const m=state.messages.get(id);if(m){m.deleted=true;m.body="";upsert(m)}}
function isNearBottom(){return list.scrollHeight-list.scrollTop-list.clientHeight<100}
function startReply(msg){state.replyTo=msg.messageId;$("#reply-name").textContent=msg.displayName;$("#reply-bar").hidden=false;input.focus()}
function cancelReply(){state.replyTo=null;$("#reply-bar").hidden=true}
async function sendMessage(){const body=input.value.trim();if(!body)return;send.disabled=true;try{await api("/global-chat/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body,replyTo:state.replyTo})});input.value="";input.style.height="auto";$("#char-count").textContent="0";cancelReply();state.stickToBottom=true}catch(e){toast(e.message)}finally{send.disabled=false;input.focus()}}
async function react(id,emoji){try{const r=await api(`/global-chat/messages/${id}/reaction`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({emoji})});upsert(r.message)}catch(e){toast(e.message)}}
function openReactionMenu(event,msg){const menu=$("#context-menu");menu.replaceChildren();["👍","❤️","😂","😮","👏","🔥"].forEach(e=>{const b=document.createElement("button");b.type="button";b.textContent=e;b.addEventListener("click",()=>{menu.hidden=true;react(msg.messageId,e)});menu.append(b)});placeMenu(menu,event)}
function openContextMenu(event,msg){const menu=$("#context-menu");menu.replaceChildren();const add=(label,fn,cls="")=>{const b=document.createElement("button");b.type="button";b.textContent=label;b.className=cls;b.addEventListener("click",()=>{menu.hidden=true;fn()});menu.append(b)};add("↩ Odpowiedz",()=>startReply(msg));add("📋 Kopiuj tekst",()=>navigator.clipboard?.writeText(msg.body).then(()=>toast("Skopiowano wiadomość.")));if(msg.userId===state.me?.userId){add("✎ Edytuj",()=>editMessage(msg));add("🗑 Usuń",()=>deleteMessage(msg),"danger")}else add("⚑ Zgłoś",()=>reportMessage(msg),"danger");placeMenu(menu,event)}
function placeMenu(menu,event){menu.hidden=false;const x=Math.min(event.clientX,innerWidth-190),y=Math.min(event.clientY,innerHeight-220);menu.style.left=`${x}px`;menu.style.top=`${y}px`}
async function editMessage(msg){const next=prompt("Edytuj wiadomość:",msg.body);if(next===null||!next.trim()||next.trim()===msg.body)return;try{const r=await api(`/global-chat/messages/${msg.messageId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({body:next.trim()})});upsert(r.message)}catch(e){toast(e.message)}}
async function deleteMessage(msg){if(!confirm("Usunąć tę wiadomość z chatu?"))return;try{await api(`/global-chat/messages/${msg.messageId}`,{method:"DELETE"});removeMessage(msg.messageId)}catch(e){toast(e.message)}}
async function reportMessage(msg){const reason=prompt("Powód zgłoszenia (np. spam, obraźliwe treści, podszywanie się):","spam");if(reason===null)return;try{await api(`/global-chat/messages/${msg.messageId}/report`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reason})});toast("Zgłoszenie zostało zapisane do weryfikacji.")}catch(e){toast(e.message)}}
async function initialLoad(){const r=await api("/global-chat/messages?limit=100");state.messages.clear();state.order=[];r.messages.forEach(m=>{state.messages.set(m.messageId,m);state.order.push(m.messageId)});setPresence(r.online);renderAll(true)}
function connectEvents(){if(state.eventSource)state.eventSource.close();const es=new EventSource("/global-chat/events",{withCredentials:true});state.eventSource=es;const head=$(".conversation-head");es.addEventListener("connected",e=>{head.classList.add("connected");$("#connection-state").innerHTML='<span class="dot"></span> Połączono — wiadomości na żywo';try{setPresence(JSON.parse(e.data).online||[])}catch{}});es.addEventListener("message.created",e=>{const data=JSON.parse(e.data);const atBottom=isNearBottom();upsert(data.message);setPresence(data.online||state.online);if(!atBottom&&data.message.userId!==state.me?.userId)$("#jump-new").hidden=false;if(state.sound&&data.message.userId!==state.me?.userId)playPing()});es.addEventListener("message.updated",e=>upsert(JSON.parse(e.data).message));es.addEventListener("message.deleted",e=>removeMessage(JSON.parse(e.data).messageId));es.onerror=()=>{head.classList.remove("connected");$("#connection-state").innerHTML='<span class="dot"></span> Ponowne łączenie…'} }
function playPing(){try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=660;gain.gain.setValueAtTime(.035,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.08);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.08)}catch{}}
function buildEmojiPanel(){const p=$("#emoji-panel");EMOJIS.forEach(e=>{const b=document.createElement("button");b.type="button";b.textContent=e;b.addEventListener("click",()=>{const start=input.selectionStart,end=input.selectionEnd;input.setRangeText(e,start,end,"end");input.dispatchEvent(new Event("input"));input.focus()});p.append(b)})}
function bind(){form.addEventListener("submit",e=>{e.preventDefault();sendMessage()});input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}});input.addEventListener("input",()=>{$("#char-count").textContent=String(input.value.length);input.style.height="auto";input.style.height=`${Math.min(input.scrollHeight,130)}px`});$("#emoji-button").addEventListener("click",()=>$("#emoji-panel").hidden=!$("#emoji-panel").hidden);$("#cancel-reply").addEventListener("click",cancelReply);$("#refresh-presence").addEventListener("click",async()=>{try{setPresence((await api("/global-chat/presence")).online)}catch(e){toast(e.message)}});$("#sound-toggle").addEventListener("click",e=>{state.sound=!state.sound;e.currentTarget.setAttribute("aria-pressed",String(state.sound));e.currentTarget.textContent=state.sound?"🔔 Dźwięki":"🔕 Dźwięki"});$("#compact-toggle").addEventListener("click",e=>{document.body.classList.toggle("compact");const on=document.body.classList.contains("compact");e.currentTarget.setAttribute("aria-pressed",String(on))});$("#jump-new").addEventListener("click",()=>{list.scrollTop=list.scrollHeight;$("#jump-new").hidden=true});list.addEventListener("scroll",()=>{state.stickToBottom=isNearBottom();if(state.stickToBottom)$("#jump-new").hidden=true});document.addEventListener("click",e=>{if(!e.target.closest("#context-menu")&&!e.target.closest(".message-actions"))$("#context-menu").hidden=true;if(!e.target.closest("#emoji-panel")&&!e.target.closest("#emoji-button"))$("#emoji-panel").hidden=true});window.addEventListener("beforeunload",()=>state.eventSource?.close())}
async function init(){await loadIdentity();if(!state.me)return;buildEmojiPanel();bind();try{await initialLoad();connectEvents()}catch(e){toast(e.message);$("#connection-state").textContent="Nie udało się połączyć z chatem."}}
init();
