(()=>{function init(){const size=15,board=document.querySelector("#board"),status=document.querySelector("#status"),movesEl=document.querySelector("#moves"),blackState=document.querySelector("#black-state"),whiteState=document.querySelector("#white-state");if(!board||!status||!movesEl||!blackState||!whiteState)return;let cells=[],moves=[],turn="black",winner=null;
function renderState(){movesEl.textContent=String(moves.length);blackState.textContent=turn==="black"&&!winner?"Twój ruch":"Czekają";whiteState.textContent=turn==="white"&&!winner?"Twój ruch":"Czekają"}
function build(){board.replaceChildren();cells=Array.from({length:size},()=>Array(size).fill(null));moves=[];turn="black";winner=null;status.textContent="Gra gotowa — ruch: czarne";status.classList.remove("win");renderState();for(let r=0;r<size;r++)for(let c=0;c<size;c++){const button=document.createElement("button");button.type="button";button.className="cell";button.dataset.row=String(r);button.dataset.column=String(c);button.setAttribute("role","gridcell");button.setAttribute("aria-label",`Pole ${r+1}, ${c+1}`);board.append(button)}}
function play(r,c,button){if(winner||cells[r][c])return;const color=turn;cells[r][c]=color;moves.push({r,c,button,color});const stone=document.createElement("i");stone.className=`stone ${color}`;stone.setAttribute("aria-hidden","true");button.append(stone);if(hasFive(r,c,color)){winner=color;status.textContent=`Wygrały ${color==="black"?"czarne":"białe"}!`;status.classList.add("win")}else if(moves.length===size*size){winner="draw";status.textContent="Remis — plansza jest pełna";status.classList.add("win")}else{turn=color==="black"?"white":"black";status.textContent=`Ruch: ${turn==="black"?"czarne":"białe"}`}renderState()}
function hasFive(r,c,color){return[[1,0],[0,1],[1,1],[1,-1]].some(([dr,dc])=>1+count(r,c,dr,dc,color)+count(r,c,-dr,-dc,color)>=5)}
function count(r,c,dr,dc,color){let total=0;for(let y=r+dr,x=c+dc;y>=0&&y<size&&x>=0&&x<size&&cells[y][x]===color;y+=dr,x+=dc)total++;return total}
function undo(){const last=moves.pop();if(!last)return;cells[last.r][last.c]=null;last.button.replaceChildren();turn=last.color;winner=null;status.classList.remove("win");status.textContent=`Ruch: ${turn==="black"?"czarne":"białe"}`;renderState()}
board.addEventListener("click",event=>{const button=event.target.closest(".cell");if(!button||!board.contains(button))return;play(Number(button.dataset.row),Number(button.dataset.column),button)});
document.querySelector("#new-game")?.addEventListener("click",build);document.querySelector("#undo")?.addEventListener("click",undo);build()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init()})();
