(()=>{const roomsRoot=document.querySelector("#rooms"),playersRoot=document.querySelector("#players"),roomCount=document.querySelector("#room-count"),playerCount=document.querySelector("#player-count"),createButton=document.querySelector("#create-room");let session=null,state={rooms:[],players:[]};try{session=JSON.parse(sessionStorage.getItem("gracz-session")||"null")}catch{}
function headers(json=false){return{...(json?{"content-type":"application/json"}:{}),...(session?.token?{authorization:`Bearer ${session.token}`}:{})}}
async function api(path,options={}){const response=await fetch(path,{credentials:"same-origin",...options,headers:{...headers(Boolean(options.body)),...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message||"Nie udało się wykonać operacji.");return body}
function empty(text){const div=document.createElement("div");div.className="empty";div.textContent=text;return div}
function render(){const rooms=(state.rooms||[]).filter(room=>room.gameType==="gomoku"),players=state.players||[];roomCount.textContent=String(rooms.length);playerCount.textContent=String(players.length);roomsRoot.replaceChildren();if(!rooms.length)roomsRoot.append(empty("Brak aktywnych stołów Gomoku. Utwórz pierwszy stół."));for(const room of rooms){const row=document.createElement("div");row.style.cssText="display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:11px;border-bottom:1px solid #23343d";const info=document.createElement("div"),name=document.createElement("b"),meta=document.createElement("small");name.textContent=room.roomName;meta.style.cssText="display:block;color:#8da1ab";meta.textContent=room.status==="waiting"?"Oczekuje na drugiego gracza":"Partia rozpoczęta";info.append(name,meta);const own=room.seats?.some(seat=>seat?.id===session?.user?.userId);const button=document.createElement("button");button.textContent=own?(room.status==="playing"?"WEJDŹ DO GRY":"TWÓJ STÓŁ"):(room.status==="waiting"?"DOŁĄCZ":"GRA TRWA");button.disabled=!own&&room.status!=="waiting";button.style.cssText="padding:8px 11px;border:0;border-radius:5px;background:#18c969;color:white;font-weight:800";button.addEventListener("click",()=>openRoom(room,own));row.append(info,button);roomsRoot.append(row)}playersRoot.replaceChildren();if(!players.length)playersRoot.append(empty("Brak innych graczy online."));for(const player of players){const row=document.createElement("div");row.style.cssText="padding:9px;border-bottom:1px solid #23343d";const name=document.createElement("b"),meta=document.createElement("small");name.textContent=player.displayName;meta.style.cssText="display:block;color:#8da1ab";meta.textContent=player.status;row.append(name,meta);playersRoot.append(row)}}
async function openRoom(room,own){try{if(own&&room.gameId)return location.href=`/gomoku.html?game=${encodeURIComponent(room.gameId)}`;if(own)return;const joined=await api(`/lobby/rooms/${encodeURIComponent(room.roomId)}/join`,{method:"POST"});if(joined.gameId)location.href=`/gomoku.html?game=${encodeURIComponent(joined.gameId)}`;else await refresh()}catch(error){alert(error.message)}}
async function createRoom(){if(!session?.user)return location.href="/";createButton.disabled=true;try{const room=await api("/lobby/rooms",{method:"POST",body:JSON.stringify({roomName:`Gomoku — ${session.user.displayName}`,gameType:"gomoku",maxPlayers:2})});await refresh();if(room.gameId)location.href=`/gomoku.html?game=${encodeURIComponent(room.gameId)}`}catch(error){alert(error.message)}finally{createButton.disabled=false}}
async function refresh(){if(!session?.user){roomsRoot.replaceChildren(empty("Zaloguj się na stronie głównej, aby utworzyć stół."));playersRoot.replaceChildren(empty("Brak aktywnej sesji."));return}try{state=await api("/lobby/state");render();const own=(state.rooms||[]).find(room=>room.gameType==="gomoku"&&room.gameId&&room.seats?.some(seat=>seat?.id===session.user.userId));if(own)location.href=`/gomoku.html?game=${encodeURIComponent(own.gameId)}`}catch(error){roomsRoot.replaceChildren(empty(error.message))}}
createButton?.addEventListener("click",createRoom);refresh();setInterval(refresh,3000)})();
