(()=>{function init(){const size=15,board=document.querySelector("#board"),status=document.querySelector("#status"),movesEl=document.querySelector("#moves"),blackState=document.querySelector("#black-state"),whiteState=document.querySelector("#white-state"),newButton=document.querySelector("#new-game"),undoButton=document.querySelector("#undo"),params=new URLSearchParams(location.search),gameId=params.get("game"),online=Boolean(gameId);if(!board||!status)return;let cells=[],moves=[],turn="black",winner=null,busy=false,session=null,realtimeAbort=null,reconnectTimer=null,reconnectAttempt=0;try{session=JSON.parse(sessionStorage.getItem("gracz-session")||"null")}catch{}
function headers(json=false){return{...(json?{"content-type":"application/json"}:{}),...(session?.token?{authorization:`Bearer ${session.token}`}:{})}}
async function api(path,options={}){const response=await fetch(path,{credentials:"same-origin",...options,headers:{...headers(Boolean(options.body)),...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message||"Błąd serwera Gomoku.");return body}
function makeBoard(){board.replaceChildren();cells=Array.from({length:size},()=>Array(size).fill(null));for(let r=0;r<size;r++)for(let c=0;c<size;c++){const button=document.createElement("button");button.type="button";button.className="cell";button.dataset.row=String(r);button.dataset.column=String(c);button.setAttribute("role","gridcell");button.setAttribute("aria-label",`Pole ${r+1}, ${c+1}`);board.append(button)}}
function putStone(button,color){button.replaceChildren();const stone=document.createElement("i");stone.className=`stone ${color}`;stone.setAttribute("aria-hidden","true");button.append(stone)}
function buttonAt(row,column){return board.children[row*size+column]}
function renderLocalState(){movesEl.textContent=String(moves.length);blackState.textContent=turn==="black"&&!winner?"Twój ruch":"Czekają";whiteState.textContent=turn==="white"&&!winner?"Twój ruch":"Czekają"}
function buildLocal(){makeBoard();moves=[];turn="black";winner=null;status.textContent="Gra lokalna — ruch: czarne";status.classList.remove("win");newButton.disabled=false;undoButton.disabled=false;renderLocalState()}
function playLocal(r,c,button){if(winner||cells[r][c])return;const color=turn;cells[r][c]=color;moves.push({r,c,button,color});putStone(button,color);if(hasFive(moves,r,c,color)){winner=color;status.textContent=`Wygrały ${color==="black"?"czarne":"białe"}!`;status.classList.add("win")}else if(moves.length===size*size){winner="draw";status.textContent="Remis — plansza jest pełna";status.classList.add("win")}else{turn=color==="black"?"white":"black";status.textContent=`Ruch: ${turn==="black"?"czarne":"białe"}`}renderLocalState()}
function undoLocal(){const last=moves.pop();if(!last)return;cells[last.r][last.c]=null;last.button.replaceChildren();turn=last.color;winner=null;status.classList.remove("win");status.textContent=`Ruch: ${turn==="black"?"czarne":"białe"}`;renderLocalState()}
let onlineView=null,lastRenderedRevision=-1;
function renderOnline(view){const incomingRevision=Number(view?.revision);if(!Number.isInteger(incomingRevision)||incomingRevision<0||incomingRevision<=lastRenderedRevision)return false;onlineView=view;makeBoard();for(const move of view.moves||[]){cells[move.row][move.column]=move.color;putStone(buttonAt(move.row,move.column),move.color)}lastRenderedRevision=incomingRevision;for(const button of board.children){const row=Number(button.dataset.row),column=Number(button.dataset.column),occupied=Boolean(cells[row]?.[column]);button.disabled=view.status!=="active"||!view.canMove||occupied;button.setAttribute("aria-disabled",String(button.disabled))}movesEl.textContent=String(view.moves?.length||0);const myColor=view.color,turnName=view.turn==="black"?"czarne":"białe";blackState.textContent=view.players.black.displayName+(myColor==="black"?" (Ty)":"");whiteState.textContent=view.players.white.displayName+(myColor==="white"?" (Ty)":"");status.classList.toggle("win",view.status!=="active");if(view.status==="finished")status.textContent=`Wygrały ${view.winner==="black"?"czarne":"białe"}!`;else if(view.status==="draw")status.textContent="Remis";else status.textContent=view.canMove?`Twój ruch — ${turnName}`:`Ruch przeciwnika — ${turnName}`;document.querySelector(".mode-note span").innerHTML="<strong>Gra online</strong> — dwóch niezależnych, zalogowanych graczy.";newButton.disabled=true;undoButton.disabled=true;return true}
async function playOnline(row,column){if(busy||!onlineView?.canMove||onlineView.status!=="active"||cells[row]?.[column])return;busy=true;const requestId=crypto.randomUUID();try{const view=await api(`/gomoku/games/${encodeURIComponent(gameId)}/moves`,{method:"POST",body:JSON.stringify({row,column,requestId})});renderOnline(view)}catch(error){status.textContent=error.message}finally{busy=false}}
function handleRealtimeBlock(block){let event="message",data="";for(const line of block.split("\n")){if(line.startsWith("event:"))event=line.slice(6).trim();else if(line.startsWith("data:"))data+=line.slice(5).trim()}if(!data||!(event==="gomoku.snapshot"||event==="gomoku.updated"))return false;try{renderOnline(JSON.parse(data));if(event==="gomoku.snapshot")reconnectAttempt=0;return true}catch{return false}}
function reconnectDelayMs(){const base=Math.min(8000,500*(2**Math.min(reconnectAttempt,4))),jitter=Math.floor(Math.random()*(Math.min(2000,Math.max(250,base/2))+1));reconnectAttempt=Math.min(reconnectAttempt+1,8);return Math.min(10000,base+jitter)}
async function connectRealtime(){if(realtimeAbort||!online)return;const controller=new AbortController();realtimeAbort=controller;try{const response=await fetch(`/gomoku/games/${encodeURIComponent(gameId)}/events`,{credentials:"same-origin",headers:headers(false),signal:controller.signal});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error?.message||"Realtime Gomoku jest niedostępny.")}if(!response.body)throw new Error("Realtime Gomoku jest niedostępny.");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";for(;;){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let boundary;while((boundary=buffer.indexOf("\n\n"))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);handleRealtimeBlock(block)}}}catch(error){if(!controller.signal.aborted){status.textContent=error.message||"Ponowne łączenie z serwerem…"}}finally{if(realtimeAbort===controller)realtimeAbort=null;if(!controller.signal.aborted&&online){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>void connectRealtime(),reconnectDelayMs())}}}
function hasFive(list,row,column,color){const occupied=new Set(list.filter(move=>move.color===color).map(move=>`${move.r}:${move.c}`));return[[1,0],[0,1],[1,1],[1,-1]].some(([dr,dc])=>1+count(occupied,row,column,dr,dc)+count(occupied,row,column,-dr,-dc)>=5)}
function count(set,row,column,dr,dc){let total=0;for(let r=row+dr,c=column+dc;set.has(`${r}:${c}`);r+=dr,c+=dc)total++;return total}
board.addEventListener("click",event=>{const button=event.target.closest(".cell");if(!button||!board.contains(button))return;const row=Number(button.dataset.row),column=Number(button.dataset.column);if(online)void playOnline(row,column);else playLocal(row,column,button)});
newButton?.addEventListener("click",()=>{if(!online)buildLocal()});undoButton?.addEventListener("click",()=>{if(!online)undoLocal()});
if(online){if(!session?.user){status.textContent="Zaloguj się, aby wejść do partii online.";status.classList.add("win");return}makeBoard();status.textContent="Łączenie z drugim graczem…";void connectRealtime();addEventListener("beforeunload",()=>{clearTimeout(reconnectTimer);realtimeAbort?.abort()},{once:true})}else buildLocal()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init()})();