const state={me:null,tournaments:[],view:"all",game:"all",format:"all",query:"",detail:null};
const $=(s)=>document.querySelector(s);
const fmtGame={warcaby:"Warcaby",gomoku:"Gomoku",szachy:"Szachy"};
const fmtFormat={swiss:"Szwajcarski",knockout:"Pucharowy",round_robin:"Każdy z każdym"};
const fmtStatus={registration:"Zapisy otwarte",live:"Trwa",finished:"Zakończony"};
const gameIcon={warcaby:"⛀",gomoku:"◉",szachy:"♟"};
function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),3000)}
async function api(path,options={}){const r=await fetch(path,{credentials:"same-origin",headers:{accept:"application/json",...(options.headers||{})},...options});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error?.message||`Błąd ${r.status}`);return b}
async function loadIdentity(){try{const r=await api("/auth/me");state.me=r.user;$("#identity").textContent=`${r.user.displayName} (@${r.user.userId})`}catch{location.replace("/")}}
function dt(value){if(!value)return"Termin ustala organizator";return new Intl.DateTimeFormat("pl-PL",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
function pct(t){return Math.min(100,Math.round((t.playerCount/Math.max(1,t.maxPlayers))*100))}
function filtered(){return state.tournaments.filter(t=>state.view==="all"||state.view==="mine"?state.view!=="mine"||t.joined:t.status===state.view).filter(t=>state.game==="all"||t.game===state.game).filter(t=>state.format==="all"||t.format===state.format).filter(t=>!state.query||`${t.title} ${t.ownerName} ${t.description}`.toLowerCase().includes(state.query))}
function renderCounts(){const a=state.tournaments;$("#count-all").textContent=a.length;$("#count-live").textContent=a.filter(t=>t.status==="live").length;$("#count-open").textContent=a.filter(t=>t.status==="registration").length;$("#count-mine").textContent=a.filter(t=>t.joined).length;$("#count-finished").textContent=a.filter(t=>t.status==="finished").length;$("#stat-live").textContent=a.filter(t=>t.status==="live").length;$("#stat-players").textContent=a.reduce((n,t)=>n+t.playerCount,0)}
function card(t){const el=document.createElement("article");el.className=`t-card ${t.status}`;const badge=`<span class="status-badge ${t.status}">${fmtStatus[t.status]||t.status}</span>`;el.innerHTML=`<div class="t-card-top"><div class="game-icon">${gameIcon[t.game]||"🎮"}</div><div class="t-title"><h3></h3><p>Organizator: <b></b> · ${dt(t.startsAt)}</p></div>${badge}</div><p class="t-description"></p><div class="meta-grid"><div><b>${fmtGame[t.game]||t.game}</b><span>gra</span></div><div><b>${fmtFormat[t.format]||t.format}</b><span>system</span></div><div><b>${t.timeControl}</b><span>tempo</span></div><div><b>${t.currentRound||0}/${t.rounds}</b><span>runda</span></div></div><div class="capacity"><div class="capacity-head"><span>Uczestnicy</span><b>${t.playerCount}/${t.maxPlayers}</b></div><div class="progress"><i style="width:${pct(t)}%"></i></div></div><div class="t-actions"><button class="details">Szczegóły i tabela</button><button class="join ${t.joined?"joined":""}">${t.joined?"✓ Zapisany":t.status==="registration"?"Dołącz":"Otwórz"}</button></div>`;
el.querySelector("h3").textContent=t.title;el.querySelector(".t-title b").textContent=t.ownerName;el.querySelector(".t-description").textContent=t.description||"Turniej społeczności Gracz.pl.";el.querySelector(".details").addEventListener("click",()=>openDetail(t.tournamentId));el.querySelector(".join").addEventListener("click",async()=>{if(t.status!=="registration"||t.joined)return openDetail(t.tournamentId);try{await api(`/tournaments/${t.tournamentId}/join`,{method:"POST"});toast("Zapisano Cię do turnieju.");await refresh();openDetail(t.tournamentId)}catch(e){toast(e.message)}});return el}
function render(){renderCounts();const root=$("#tournament-list");root.replaceChildren();const list=filtered();if(!list.length){const e=document.createElement("div");e.className="empty";e.innerHTML="<strong>Brak turniejów</strong><span>Zmień filtry albo utwórz nowe wydarzenie.</span>";root.append(e);return}list.forEach(t=>root.append(card(t)))}
async function refresh(){try{const r=await api("/tournaments");state.tournaments=r.tournaments;render()}catch(e){toast(e.message)}}
function detailHeader(d){const t=d.tournament;return `<header><div><p class="eyebrow">${fmtGame[t.game]||t.game} · ${fmtFormat[t.format]||t.format}</p><h2>${escapeHtml(t.title)}</h2><p>${fmtStatus[t.status]} · ${dt(t.startsAt)} · organizator ${escapeHtml(t.ownerName)}</p></div><button class="x" data-close>×</button></header>`}
function standingsTable(players){if(!players.length)return'<div class="empty"><strong>Brak uczestników</strong></div>';return `<table class="standings"><thead><tr><th>#</th><th>Gracz</th><th>PKT</th><th>W</th><th>R</th><th>P</th><th>Buchholz</th></tr></thead><tbody>${players.map((p,i)=>`<tr><td class="rank">${i+1}</td><td>${escapeHtml(p.displayName)} <small>@${escapeHtml(p.userId)}</small></td><td class="score">${p.points}</td><td>${p.wins}</td><td>${p.draws}</td><td>${p.losses}</td><td>${p.buchholz}</td></tr>`).join("")}</tbody></table>`}
function matchesTable(d){const groups=new Map();d.matches.forEach(m=>{if(!groups.has(m.round))groups.set(m.round,[]);groups.get(m.round).push(m)});if(!groups.size)return'<div class="empty"><strong>Parowania pojawią się po starcie turnieju</strong></div>';return [...groups].map(([round,matches])=>`<section class="round-section"><div class="round-label">RUNDA ${round}</div><table class="matches"><thead><tr><th>Stół</th><th>Białe</th><th>Wynik</th><th>Czarne</th><th>Status</th></tr></thead><tbody>${matches.map(m=>`<tr><td>${m.board}</td><td>${escapeHtml(m.whiteName||"—")}</td><td class="match-result">${resultCell(d,m)}</td><td>${escapeHtml(m.blackName||"BYE")}</td><td>${m.status==="completed"?"Zakończona":"Do rozegrania"}</td></tr>`).join("")}</tbody></table></section>`).join("")}
function resultCell(d,m){if(m.result)return`<b>${m.result}</b>`;const can=d.tournament.ownerId===state.me.userId||m.whiteId===state.me.userId||m.blackId===state.me.userId;if(!can)return"—";return `<button data-result="1-0" data-match="${m.matchId}">1-0</button> <button data-result="1/2-1/2" data-match="${m.matchId}">½-½</button> <button data-result="0-1" data-match="${m.matchId}">0-1</button>`}
async function openDetail(id){try{const d=await api(`/tournaments/${id}`);state.detail=d;const t=d.tournament,meOwner=t.ownerId===state.me.userId;const controls=t.status==="registration"?`${t.joined&&!meOwner?'<button data-leave>Wycofaj zapis</button>':''}${!t.joined?'<button class="primary" data-join>Dołącz do turnieju</button>':''}${meOwner?'<button class="primary" data-start>Rozpocznij turniej</button>':''}`:"";const body=`${detailHeader(d)}<div class="detail-body"><section class="detail-hero"><div><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(t.description||"Turniej społeczności Gracz.pl.")}</p><div class="detail-chips"><span>🎮 ${fmtGame[t.game]}</span><span>⚙ ${fmtFormat[t.format]}</span><span>⏱ ${t.timeControl}</span><span>👥 ${t.playerCount}/${t.maxPlayers}</span><span>🔁 ${t.rounds} rund</span><span>${t.rated?"★ Rankingowy":"◇ Towarzyski"}</span></div></div><div class="detail-controls">${controls}</div></section><div class="detail-tabs"><button class="active" data-detail-tab="standings">Klasyfikacja</button><button data-detail-tab="pairings">Parowania</button><button data-detail-tab="info">Informacje</button></div><section data-detail-panel="standings">${standingsTable(d.players)}</section><section data-detail-panel="pairings" hidden>${matchesTable(d)}</section><section data-detail-panel="info" hidden><div class="info-card"><b>Zasady turnieju</b><span>Format: ${fmtFormat[t.format]}</span><span>Tempo: ${t.timeControl}</span><span>Liczba rund: ${t.rounds}</span><span>Ranking: ${t.rated?"tak":"nie"}</span><span>Widoczność: ${t.visibility==="public"?"publiczna":"tylko z linku"}</span></div></section></div>`;const dialog=$("#detail-dialog"),root=$("#detail-content");root.innerHTML=body;bindDetail(dialog,d);dialog.showModal()}catch(e){toast(e.message)}}
function bindDetail(dialog,d){dialog.querySelector("[data-close]").addEventListener("click",()=>dialog.close());dialog.querySelectorAll("[data-detail-tab]").forEach(b=>b.addEventListener("click",()=>{dialog.querySelectorAll("[data-detail-tab]").forEach(x=>x.classList.toggle("active",x===b));dialog.querySelectorAll("[data-detail-panel]").forEach(p=>p.hidden=p.dataset.detailPanel!==b.dataset.detailTab)}));dialog.querySelector("[data-join]")?.addEventListener("click",async()=>{try{await api(`/tournaments/${d.tournament.tournamentId}/join`,{method:"POST"});toast("Zapisano do turnieju.");dialog.close();await refresh();openDetail(d.tournament.tournamentId)}catch(e){toast(e.message)}});dialog.querySelector("[data-leave]")?.addEventListener("click",async()=>{if(!confirm("Wycofać się z turnieju?"))return;try{await api(`/tournaments/${d.tournament.tournamentId}/leave`,{method:"POST"});toast("Wycofano zapis.");dialog.close();await refresh()}catch(e){toast(e.message)}});dialog.querySelector("[data-start]")?.addEventListener("click",async()=>{if(!confirm("Rozpocząć turniej i wygenerować pierwszą rundę?"))return;try{await api(`/tournaments/${d.tournament.tournamentId}/start`,{method:"POST"});toast("Turniej rozpoczęty.");dialog.close();await refresh();openDetail(d.tournament.tournamentId)}catch(e){toast(e.message)}});dialog.querySelectorAll("[data-result]").forEach(b=>b.addEventListener("click",async()=>{if(!confirm(`Zapisać wynik ${b.dataset.result}?`))return;try{await api(`/tournaments/${d.tournament.tournamentId}/matches/${b.dataset.match}/result`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({result:b.dataset.result})});toast("Wynik zapisany.");dialog.close();await refresh();openDetail(d.tournament.tournamentId)}catch(e){toast(e.message)}}))}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function defaultStart(){const d=new Date(Date.now()+24*60*60*1000);d.setMinutes(Math.ceil(d.getMinutes()/15)*15,0,0);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function bind(){document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===b));state.view=b.dataset.view;render()}));$("#search").addEventListener("input",e=>{state.query=e.target.value.trim().toLowerCase();render()});$("#game-filter").addEventListener("change",e=>{state.game=e.target.value;render()});$("#format-filter").addEventListener("change",e=>{state.format=e.target.value;render()});$("#refresh").addEventListener("click",refresh);const cd=$("#create-dialog");const form=$("#create-form");const closeCreate=()=>{if(cd.open)cd.close();form.reset()};$("#create-tournament").addEventListener("click",()=>{$("#ct-start").value=defaultStart();cd.showModal()});form.querySelector(".x").addEventListener("click",e=>{e.preventDefault();closeCreate()});form.querySelector('footer button[value="cancel"]').addEventListener("click",e=>{e.preventDefault();closeCreate()});cd.addEventListener("click",e=>{if(e.target===cd)closeCreate()});cd.addEventListener("cancel",e=>{e.preventDefault();closeCreate()});form.addEventListener("submit",async e=>{if(e.submitter?.value==="cancel"){e.preventDefault();closeCreate();return}e.preventDefault();const payload={title:$("#ct-title").value,game:$("#ct-game").value,format:$("#ct-format").value,maxPlayers:Number($("#ct-max").value),rounds:Number($("#ct-rounds").value),timeControl:$("#ct-time").value,startsAt:$("#ct-start").value?new Date($("#ct-start").value).toISOString():null,visibility:$("#ct-visibility").value,rated:$("#ct-rated").checked,description:$("#ct-description").value};const btn=$("#create-submit");btn.disabled=true;try{const r=await api("/tournaments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});cd.close();form.reset();toast("Turniej został utworzony.");await refresh();openDetail(r.tournament.tournamentId)}catch(err){toast(err.message)}finally{btn.disabled=false}})}
async function init(){await loadIdentity();if(!state.me)return;bind();await refresh();setInterval(refresh,30000)}
init();
